# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 838a733a8cf6b558a8cb64b1c0935a4974cd1115badc294b79cf254c3b5e009ccd6d008ee25b42c924cd89e93caba591dd79c58ce52a1da3a724fc3aea56563d

test:
  secret_key_base: 94dfabbc5b9fbf8e0a5a7698d4ac65498c745d94e7dcfc992cd35789406f4838e724f5e93de9a786f7a5521a1e85526be2d914a5da0692b9fcf6b96f7163bcb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
